quarkus:
  log:
    min-level: DEBUG
    level: DEBUG
    category:
      "org.jboss.resteasy.reactive.client.logging":
        min-level: TRACE
        level: TRACE
mp:
  messaging:
    incoming:
      kafka:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        failure-strategy: ignore
        security:
          protocol: SASL_SSL
        sasl:
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username='username' password='password';
          mechanism: PLAIN
        auto:
          register:
            schemas: false
          offset:
            reset: latest
        enable:
          auto:
            commit: false
        request:
          timeout:
            ms: 30000
        heartbeat:
          interval:
            ms: 3000
        session:
          timeout:
            ms: 45000
        max:
          poll:
            records: 250
            interval:
              ms: 300000
        retry: true
        retry-max-wait: 5
        topics:
          - test

smallrye:
  config:
    secret-handler:
      jasypt:
        algorithm: PBEWITHHMACSHA512ANDAES_256
        password: password